stages:
  download:
    cmd: python cli.py download
    deps:
      - cli.py
      - download.py
    params:
      - config.json:
        - kaggle_mnist_handle
        - kaggle_mnist_train_file
        - kaggle_mnist_test_file
        - kaggle_token_file
    outs:
      - data/train/raw
      - data/test/raw

  convert:
    cmd: python cli.py convert
    deps:
      - cli.py
      - convert.py
      - data/train/raw
      - data/test/raw
    outs:
      - data/train/converted
      - data/test/converted

  augment:
    cmd: python cli.py augment
    deps:
      - data/train/converted
      - augment.py
      - cli.py
    params:
      - config.json:
        - seed
        - scrambled_copies
        - scramble_fraction
    outs:
      - data/train/augmented

  train:
    cmd: python cli.py train
    deps:
      - data/train/augmented
      - dataloader.py
      - network.py
      - train.py
      - hypers.json
    outs:
      - saved_models/scrambled_mnist.pth

  test:
    cmd: python cli.py test
    deps:
      - saved_models/scrambled_mnist.pth
      - data/test/raw
      - dataloader.py
      - network.py
      - test.py

  download_mnist_c:
    cmd: python cli.py download-mnist-c
    deps:
      - ext_tests/mnist_c/download.py
    params:
      - config.json:
        - mnist_c_main_dataset
        - mnist_c_aux_dataset
    outs:
      - data/external/raw/mnist_c
      - data/external/raw/mnist_c_leftovers


  convert_mnist_c:
    cmd: python cli.py convert-mnist-c
    deps:
      - data/external/raw/mnist_c
      - data/external/raw/mnist_c_leftovers
      - ext_tests/mnist_c/convert.py
    outs:
      - data/external/converted/mnist_c
      - data/external/converted/mnist_c_leftovers
