stages:
  setup:
    cmd: python cli.py setup
    deps:
      - hyper.json
    outs:
      - config_used.json
  
  download:
    cmd: python cli.py download
    deps:
      - download.py
      - config.py
      - hyper.json
    outs:
      - data/train/raw:
          persist: true
      - data/test/raw:
          persist: true
  
  scramble:
    cmd: python cli.py create-scrambled
    deps:
      - augment.py
      - config.py
      - hyper.json
      - data/train/raw
    outs:
      - data/train/scrambled
  
  augment:
    cmd: python cli.py create-augmented
    deps:
      - augment.py
      - config.py
      - hyper.json
      - data/train/raw
      - data/train/scrambled
    outs:
      - data/train/augmented
  
  train_original:
    cmd: python cli.py train-model --model-type robust --experiment-name original
    deps:
      - train.py
      - network.py
      - dataloader.py
      - metrics.py
      - config.py
      - hyper.json
      - data/train/raw
      - data/test/raw
    outs:
      - models/original.h5
      - checkpoints/original
    metrics:
      - metrics/original_metrics.json:
          cache: false
    plots:
      - metrics/original_training_curves.png:
          cache: false
  
  train_augmented:
    cmd: python cli.py train-model --model-type robust --experiment-name augmented
    deps:
      - train.py
      - network.py
      - dataloader.py
      - metrics.py
      - config.py
      - hyper.json
      - data/train/augmented
      - data/test/raw
    outs:
      - models/augmented.h5
      - checkpoints/augmented
    metrics:
      - metrics/augmented_metrics.json