stages:
  download_train:
    cmd: python cli.py download-train
    outs:
      - data/train/raw/train.csv
  download_test:
    cmd: python cli.py download-test
    outs:
      - data/test/raw/test.csv
  augment:
    cmd: python cli.py augment-data
    deps:
      - data/train/raw/train.csv
    outs:
      - data/train/scrambled
      - data/train/augmented
  train:
    cmd: python cli.py train-model
    deps:
      - data/train/augmented
      - hyper.json
    outs:
      - models/model.pth
  evaluate:
    cmd: python cli.py evaluate-model
    deps:
      - models/model.pth
      - data/test/raw/test.csv