stages:
  download:
    cmd: python cli.py download
    outs:
      - data/train/raw
      - data/test/raw

  convert:
    cmd: python cli.py convert
    deps:
      - data/train/raw
      - data/test/raw
    outs:
      - data/train/converted
      - data/test/converted

  augment:
    cmd: python cli.py data_augment
    deps:
      - data/train/converted
    outs:
      - data/train/augmented

  train:
    cmd: python cli.py run_train
    deps:
      - data/train/augmented
    outs:
      - model.pth

  test:
    cmd: python cli.py run_test
    deps:
      - model.pth
      - data/test/raw
