stages:
  download:
    cmd: python cli.py download
    deps:
      - cli.py
      - download.py
    params:
      - config.json:
        - kaggle_mnist_handle
        - kaggle_mnist_train_file
        - kaggle_mnist_test_file
        - kaggle_token_file
    outs:
      - data/train/raw
      - data/test/raw

  convert:
    cmd: python cli.py convert
    deps:
      - cli.py
      - convert.py
      - data/train/raw
      - data/test/raw
    outs:
      - data/train/converted
      - data/test/converted

  augment:
    cmd: python cli.py augment
    deps:
      - data/train/converted
      - augment.py
      - cli.py
    params:
      - config.json:
        - seed
        - scrambled_copies
        - scramble_fraction
    outs:
      - data/train/augmented

  train:
    cmd: python cli.py train
    deps:
      - data/train/converted
      - dataloader.py
      - network.py
      - train.py
    outs:
      - saved_models/scrambled_mnist.pth

  test:
    cmd: python cli.py test
    deps:
      - saved_models/scrambled_mnist.pth
      - data/test/raw
      - dataloader.py
      - network.py
      - test.py
